import * as fs from 'fs';
import * as path from 'path';
import { SlashCommand } from './registry.js';
import { TrizDeps } from '../infrastructure/config/di.js';

export const autoCommand: SlashCommand = {
  name: 'auto',
  description: 'Start/continue an AutoResearch iteration loop: propose → act → evaluate → ratchet',
  usage: '/auto <research question or hypothesis> [--iterations N]',
  async execute(args: string, deps: TrizDeps, emit: (type: string, data: any) => void, signal: AbortSignal) {
    const root = deps.phaseWriter.getWorkspaceRoot();
    if (!root) {
      emit('token', { tokenType: 'Text', text: 'No workspace root. Run /init first.' });
      emit('done', {});
      return;
    }

    const autoDir = path.join(root, '08_AutoResearch');
    const experimentsDir = path.join(autoDir, 'experiments');
    try {
      fs.mkdirSync(experimentsDir, { recursive: true });
    } catch {
      emit('token', { tokenType: 'Text', text: `Cannot create ${experimentsDir}. Check filesystem permissions.` });
      emit('done', {});
      return;
    }
    if (signal.aborted) { emit('done', {}); return; }

    const existingLogs = fs.readdirSync(experimentsDir)
      .filter(f => f.startsWith('log_') && f.endsWith('.md'))
      .sort();
    const nextIter = existingLogs.length + 1;

    const scopePath = path.join(autoDir, 'scope.md');
    const evalPath = path.join(autoDir, 'eval.md');

    if (!fs.existsSync(scopePath) || !fs.existsSync(evalPath)) {
      emit('token', { tokenType: 'Text', text: [
        '## /auto: Setup Required',
        '',
        'AutoResearch loop requires two setup files. Create them manually or run `/init`:',
        '',
        '| File | Path | Purpose |',
        '|------|------|---------|',
        '| scope.md | `08_AutoResearch/scope.md` | Research scope, constraints, success criteria, mutation surface',
        '| eval.md | `08_AutoResearch/eval.md` | Fixed evaluation metric, protocol, accept/reject criteria',
        '',
        'Then run `/auto <hypothesis>` to start iterating.',
      ].join('\n') });
      emit('done', {});
      return;
    }

    const iterMatch = args.match(/--iterations\s+(\d+)/i);
    const maxIterations = iterMatch ? Math.min(parseInt(iterMatch[1]!, 10), 20) : 5;
    const cleanArgs = args.replace(/--iterations\s+\d+/i, '').trim();
    const hypothesis = cleanArgs || `Iteration ${nextIter}: continue optimizing based on previous results`;

    // Write hypothesis to file so agent discovers it on next chat
    const hypothesisPath = path.join(autoDir, 'current_hypothesis.md');
    try {
      fs.writeFileSync(hypothesisPath, [
        `# Current Hypothesis (Iteration ${nextIter})`,
        '',
        hypothesis,
        '',
        `**Max iterations:** ${maxIterations}`,
        `**Started:** ${new Date().toISOString()}`,
        '',
        '> Auto-generated by /auto. The agent MUST read this file at the start of the next chat.',
        '> After reading, the agent MUST delete this file to avoid stale hypotheses.',
      ].join('\n'), 'utf-8');
    } catch {
      emit('token', { tokenType: 'Text', text: 'Cannot write hypothesis file.' });
      emit('done', {});
      return;
    }
    if (signal.aborted) { emit('done', {}); return; }

    emit('token', { tokenType: 'Text', text: [
      `## AutoResearch Iteration ${nextIter}`,
      '',
      `**Hypothesis written to** \`08_AutoResearch/current_hypothesis.md\``,
      '',
      'The agent will pick up the hypothesis on the next chat. Say "go" to start the loop.',
      '',
      '| Setting | Value |',
      '|---------|-------|',
      `| Hypothesis | ${hypothesis} |`,
      `| Max iterations | ${maxIterations} |`,
      `| Scope | \`08_AutoResearch/scope.md\` |`,
      `| Eval | \`08_AutoResearch/eval.md\` |`,
      `| Logs | \`08_AutoResearch/experiments/\` |`,
      '',
    ].join('\n') });
    emit('done', {});
  },
};
