import type { Language } from '../../domain/shared/i18n.js';

export type LocalizedReport = {
  headerTitle: (problem: string) => string;
  sectionExecutiveSummary: string;
  sectionKeyFindings: string;
  sectionRecommendations: string;
  sectionConclusion: string;
  sectionNextSteps: string;
  sectionMethodology: string;
  sectionToc: string;
  footerGeneratedBy: string;
  priorityHigh: string;
  priorityMedium: string;
  priorityLow: string;
  sectionTitleNormalizer: (englishTitle: string) => string;
  appendixTitle: string;
  appendixDataHeading: string;
  appendixStatsHeading: string;
  appendixLayoutHeading: string;
  appendixDataBlurb: string;
  appendixChartsBlurb: string;
  appendixCodeBlurb: string;
  referencesAnnotationsBlurb: string;
};

const EN: LocalizedReport = {
  headerTitle: (problem) => `**Problem**: ${problem}`,
  sectionExecutiveSummary: 'Executive Summary',
  sectionKeyFindings: 'Key Findings',
  sectionRecommendations: 'Recommendations',
  sectionConclusion: 'Conclusion',
  sectionNextSteps: 'Next Steps',
  sectionMethodology: 'Methodology',
  sectionToc: 'Table of Contents',
  footerGeneratedBy: '*Auto-generated by TRP framework*',
  priorityHigh: '🔴 High',
  priorityMedium: '🟡 Medium',
  priorityLow: '🟢 Low',
  sectionTitleNormalizer: (t) => t,
  appendixTitle: '# Appendix',
  appendixDataHeading: '## Data Files',
  appendixStatsHeading: '## Cross-Phase Stats',
  appendixLayoutHeading: '## Layout',
  appendixDataBlurb: 'Raw data files copied from earlier phases (search results, contradictions, solutions, trends).',
  appendixChartsBlurb: 'Reserved for SVG/PNG figures (S-curves, TRL radar, contradiction heat maps, trend timelines).',
  appendixCodeBlurb: 'Code snippets and notebooks referenced in the report.',
  referencesAnnotationsBlurb: 'Reading notes for cited works, named to match `library.bib` keys (e.g. `smith23.md`).',
};

const ZH: LocalizedReport = {
  headerTitle: (problem) => `**研究问题**: ${problem}`,
  sectionExecutiveSummary: '执行摘要',
  sectionKeyFindings: '关键发现',
  sectionRecommendations: '建议',
  sectionConclusion: '结论',
  sectionNextSteps: '下一步行动',
  sectionMethodology: '研究方法论',
  sectionToc: '目录',
  footerGeneratedBy: '*由 TRP 框架自动生成*',
  priorityHigh: '🔴 高优先级',
  priorityMedium: '🟡 中优先级',
  priorityLow: '🟢 低优先级',
  sectionTitleNormalizer: (t) => {
    const lower = t.toLowerCase().trim();
    for (const [pat, zh] of SECTION_TITLE_MAP) {
      if (pat.test(lower)) return zh;
    }
    return t;
  },
  appendixTitle: '# 附录',
  appendixDataHeading: '## 数据文件',
  appendixStatsHeading: '## 跨阶段统计',
  appendixLayoutHeading: '## 目录结构',
  appendixDataBlurb: '从先前阶段复制的原始数据文件（检索结果、矛盾、方案、趋势）。',
  appendixChartsBlurb: '预留 SVG/PNG 图表位置（S 曲线、TRL 雷达、矛盾热图、趋势时间线）。',
  appendixCodeBlurb: '报告中引用的代码片段与脚本。',
  referencesAnnotationsBlurb: '已引用文献的阅读笔记，命名与 `library.bib` 键保持一致（如 `smith23.md`）。',
};

const SECTION_TITLE_MAP: Array<[RegExp, string]> = [
  [/^executive\s*summary$/, '执行摘要'],
  [/^introduction$/, '引言'],
  [/^literature\s*review$/, '文献综述'],
  [/^related\s*work$/, '相关工作'],
  [/^background$/, '研究背景'],
  [/^technology\s*maturity\s*assessment$/, '技术成熟度评估'],
  [/^trl\s*[&and]*\s*(technology\s*)?maturity$/, 'TRL 技术成熟度评估'],
  [/^contradiction\s*[&and]*\s*bottleneck\s*analysis$/, '矛盾与瓶颈分析'],
  [/^contradiction\s*analysis$/, '矛盾分析'],
  [/^bottleneck\s*analysis$/, '瓶颈分析'],
  [/^innovation\s*solutions?$/, '创新解决方案'],
  [/^proposed\s*solutions?$/, '建议方案'],
  [/^technology\s*trends?\s*[&and]*\s*roadmap$/, '技术趋势与路线图'],
  [/^trends?\s*[&and]*\s*roadmap$/, '趋势与路线图'],
  [/^technology\s*trends?$/, '技术趋势'],
  [/^roadmap$/, '技术路线图'],
  [/^conclusion$/, '结论'],
  [/^recommendations?$/, '建议'],
  [/^next\s*steps?$/, '下一步行动'],
  [/^methodology$/, '研究方法论'],
  [/^methods?$/, '研究方法'],
  [/^discussion$/, '讨论'],
  [/^results?$/, '结果'],
  [/^abstract$/, '摘要'],
  [/^patents?\s*landscape$/, '专利景观'],
  [/^evolution\s*trends?$/, '技术进化趋势'],
  [/^feasibility\s*analysis$/, '可行性分析'],
  [/^risk\s*analysis$/, '风险分析'],
];

export function getLocalizedReport(language: Language): LocalizedReport {
  return language === 'zh' ? ZH : EN;
}

export function isLikelyEnglishSentence(s: string): boolean {
  if (!s) return false;
  const trimmed = s.trim();
  if (trimmed.length < 4) return false;
  const hasCJK = /[\u4e00-\u9fff]/.test(trimmed);
  if (hasCJK) return false;
  const words = trimmed.split(/\s+/);
  if (words.length < 3) return false;
  const ascii = trimmed.replace(/[^a-zA-Z]/g, '');
  if (ascii.length < words.length * 2) return false;
  return /[A-Z]/.test(trimmed[0]!) && /\b(the|is|are|was|were|has|have|and|with|that|this|for|from|to|of|in|on)\b/i.test(trimmed);
}
